### ISSUE TITLE
Unable to Read my excel file of .xlsx format.

### ISSUE THREAD

**Issue by Bikasa** [DaSpawn/xlsx-stream-reader#8] opened 2017-05-23 14:02 UTC
@DaSpawn ,
    I am trying to read the attached excel file using this module,But I am unable to read the file as it is throwing error.Please find the  attached file below .I think it is the issue with the numeric fields..Not sure.
[Export_201605 (1).xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/1022384/Export_201605.1.xlsx)
[Export_201605 (13).xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/1025280/Export_201605.13.xlsx)

**Comment by DaSpawn** [comment] 2017-05-25 15:54
What is the error being thrown?  What version of the module are you using?  I have tried both sheets and they both read no problem on the latest version (0.9.9)

**Comment by Bikasa** [comment] 2017-05-25 17:14
@DaSpawn ,
I have tried this sheet by downloading from our application.One thing I have observed that if I jsut try to read the file directly after downloading ,it is getting failed.But if I open the same file and and click on save icon of the Sheet ,and the try to read the file the I am able to read the sheet correctly.Don't know if the issue is with the sheet or with module.

I am attaching two new file ,one is before clicking save button,and another is after clicking save button.Can you please help me out to find the issue ,if it is with the sheet or module.

[F1_with_Save.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/1029703/F1_with_Save.xlsx)
[F1_without_Save.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/1029704/F1_without_Save.xlsx)
![z11](https://cloud.githubusercontent.com/assets/23119692/26461709/bca7c812-419b-11e7-874d-630d27cca691.png)

**Comment by DaSpawn** [comment] 2017-05-25 17:57
I have seen this issue randomly and had not pinned it down yet, I will look further.  What type of application was this generated by (name if app if possible)?

**Comment by Bikasa** [comment] 2017-05-29 14:15
I am using xlsx module (https://www.npmjs.com/package/xlsx) for  generating my excel sheet.

**Comment by jcready** [comment] 2017-05-29 15:18
[Here is the diff between the two](https://github.com/jcready/xlsx-compare-test/commit/df35858496e5efe9a169eb4bb50fd6fec00e37ed) after adding some whitespace to make the diff helpful.

**Comment by reviewher** [comment] 2017-05-29 17:18
XLSX supports two types of strings: shared strings and inline strings.  `xlsx` generates inline strings normally.  The [`bookSST write option`](https://github.com/SheetJS/js-xlsx#writing-options) will build the shared string table.

Is this module handling inline strings properly?

**Comment by jcready** [comment] 2017-05-29 19:48
I believe I have found the problem which resides in worksheet.js. The problem is that the `_handleWorkSheetNode()` prototype method is responsible for emitting the `row` event, but if the last XML node in the sheet is a `row` then that last `row` event never fires. The only reason it works for the file saved with Excel is because the last node in that sheet's XML is a `pageMargins` node. I'll see if I can throw together a PR to address the problem.

**Comment by DaSpawn** [comment] 2017-05-30 18:30
Thank you very much for finding that bug, I have merged the changes and will update npm version shortly

**Comment by Bikasa** [comment] 2017-05-31 10:30
@DaSpawn , 
Can I try reading my excel sheet with the latest version (0.9.10) of the module ?

**Comment by DaSpawn** [comment] 2017-06-03 17:05
I had used your provided F1_with_Save.xlsx and F1_without_Save.xlsx in example 3 and they both read without error

What is the exact errors your are getting (trace)?

**Comment by jcready** [comment] 2017-06-04 14:34
And/or can you show us the code you're getting the error with. It would be most helpful in being able to reproduce the issue.

**Comment by Bikasa** [comment] 2017-06-07 10:11
Hi @jcready  @DaSpawn 
I am attaching the sample code in the way we used in our application and explaining where I am getting the error. 

Can you please find the sample code in below attached file.

[SampleCode.zip](https://github.com/DaSpawn/xlsx-stream-reader/files/1057660/SampleCode.zip)

**Comment by Bikasa** [comment] 2017-06-09 14:58
Hi @DaSpawn ,
Any update on this issues . Please let me know ,if anything is required  from my end  and help me out in resolving this issue.

Thanks

**Comment by DaSpawn** [comment] 2017-06-19 19:16
I have been slammed with work, will look soon as I can

**Closed** 2018-06-28 06:43 UTC
